HTML事前課題　CSSコーディング
kazuyanakata/quelcode-html pull request #2
Opened 2020-07-28 11:38 UTC by kazuyanakata

2020-07-30 02:07 UTC, piasoratech requested changes
見た目の確認などはされたでしょうか？
ざっと見ても見本とかなり差があるので、確認をしましょう。
一例として、違う部分を上げさせてもらうと
- PDFのアイコンがない　
![image](https://user-images.githubusercontent.com/57445698/88872209-a37a2b80-d254-11ea-8854-9850c150ddb7.png)

- 見た目が全く違う
![image](https://user-images.githubusercontent.com/57445698/88872228-ad9c2a00-d254-11ea-8464-4e86a2c35ea7.png)
- 画像の見えている部分が違う
![image](https://user-images.githubusercontent.com/57445698/88872282-c73d7180-d254-11ea-810a-87dc9ba330a0.png)
等がありました。
他にも見た目が違う部分が多くあったので、本家サイトと良く見比べて再度実装をお願いします。

2020-07-30 02:07 UTC, piasoratech commented on nri/index.html
> +        <p class="main-script">NRI では、企業の DX に向けた取り組みについて、既存ビジネスの業務プロセス変革に寄与する DX を「DX1.0」、デジタルで新しいビジネスモデルそのものを生み出す DX を「DX2.0」と定義しています。<br><br>
文章の行間は`br`で調節せずにCSSで調節してください。
あくまでhtmlの役割は文章構造を伝えることにあります。

2020-07-30 07:50 UTC, kazuyanakata commented
コメント箇所の修正を行いました。

修正箇所が多かったため、代表的な変更以外は全てまとめてコミット致しました。
CSSと同時にHTMLも変更しております。（以前のレビュー時に<p>タグを一つにまとめて<br>を付けようにご指示があった箇所はヒゲさんに聞いたところ分けてもいいとのことなので、元の形に戻しております）
■代表的な修正箇所
　・PDFアイコン追加
　・背景画面の可視部分変更
　・見出しアイコンの追加
　・フォント変更
■その他、文字サイズや余白、表示方法等変更

2020-07-31 00:55 UTC, piasoratech requested changes
まだ見た目部分でそろっていないところがあります。
隅々までもう一度確認してください。
なんとなく合っている状態ではなく、完璧にそろえるくらいのつもりで確認をしましょう。
- NRIの強みの部分
提出されたもの
![image](https://user-images.githubusercontent.com/57445698/88988123-edc1e200-d312-11ea-999f-75a9c8442e5f.png)
本家サイト
![image](https://user-images.githubusercontent.com/57445698/88988132-f3b7c300-d312-11ea-89d4-c0798f90d00e.png)
- PDFのボタンのサイズ
提出されたもの
![image](https://user-images.githubusercontent.com/57445698/88988162-09c58380-d313-11ea-9dd3-b6fa9dbf46e3.png)
本家サイト
![image](https://user-images.githubusercontent.com/57445698/88988171-0f22ce00-d313-11ea-9520-5e53b3b7689d.png)
- 採用情報～サイトマップまで(`>`の太さや文字の段組みなど)
提出されたもの
![image](https://user-images.githubusercontent.com/57445698/88988226-38435e80-d313-11ea-94db-1b908d5ddfce.png)
本家サイト
![image](https://user-images.githubusercontent.com/57445698/88988232-3da0a900-d313-11ea-95a1-1d9d5e358551.png)

2020-07-31 05:52 UTC, kazuyanakata commented
**コメント箇所の修正を行いました。**

前回のレビュー申請時と同様に複数箇所の修正を行い、元のHPに近い形に変更いたしました。
・文字サイズ、太さの変更
・余白等の大きさの変更
・矢印の変更
・ファビコンの変更

2020-07-31 06:02 UTC, piasoratech requested changes
- 今回の修正でFollow Usより下の部分からフッターまでの部分が左に寄ってしまっているので修正をお願いします。
![image](https://user-images.githubusercontent.com/57445698/89005124-ab15ff00-d33e-11ea-9984-0651f5cd56a5.png)
![image](https://user-images.githubusercontent.com/57445698/89005135-b23d0d00-d33e-11ea-863d-4ba3c1532dcc.png)

2020-07-31 06:22 UTC, kazuyanakata commented
**コメント箇所の修正を行いました。**
・HTMLの文章で間違っている箇所があったので変更。
・要素が中心にくるように`margin:0 auto`に変更。

2020-07-31 06:30 UTC, piasoratech approved these changes
OKです！
お疲れ様です！！！

2020-08-11 07:45 UTC, merged