家具屋サイトの作成（HTML/CSS課題③）
kazuyanakata/quelcode-html pull request #3
Opened 2020-07-30 11:12 UTC by kazuyanakata

HOMEページのHTML実装完了致しました。

2020-07-31 01:34 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-31 01:34 UTC, piasoratech commented on kaguya/home.html
> +          <p>アームストロングのテーブル入荷</p>
このあたりの`alt`の内容もう一度考えてみましょう
https://www.asobou.co.jp/blog/web/alt

2020-07-31 05:57 UTC, kazuyanakata commented
コメント箇所の修正を行いました。
・ニュース画像のalt名変更

2020-07-31 06:05 UTC, piasoratech approved these changes
OKです！
次に進みましょう！

2020-07-31 06:46 UTC, kazuyanakata commented
ニュースページ・リクルートページ・コンタクトページのHTMLの初回実装を行いました。

2020-07-31 07:33 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-31 07:33 UTC, piasoratech commented on kaguya/recruit.html
> +          <li class="footer-link-item"><a href="recruit.html">RECRUIT</a></li>
ここの順序が違うので修正お願いします！
(すいませんLGTM出したHOMEの部分も同じように間違っているので、全部確認して修正して下さい)

2020-07-31 07:38 UTC, kazuyanakata commented
**コメント箇所の修正を行いました。**
・フッターのRECRUITとCONTACTの順番変更

2020-08-05 11:42 UTC, himaru-jp requested changes

2020-08-05 11:42 UTC, himaru-jp commented on kaguya/contact.html
> +          <li class="footer-link-item"><a href="recruit.html">CONTACT</a></li>
リンク先(href属性)が逆になっています
他のページも同様のため修正をお願いします。

2020-08-05 11:48 UTC, kazuyanakata commented
**コメント箇所の修正を行いました**
・フッターのhrefの順番変更

2020-08-05 11:53 UTC, himaru-jp approved these changes
レビューOKです。

2020-08-06 00:27 UTC, kazuyanakata commented
**HOMEページのCSS初回実装を行いました。**
レビューよろしくお願いいたします。

2020-08-14 02:28 UTC, ghost reviewed
全体的に大変きれいです。
home.htmlから確認したので、1発LGTMかと思って慌てました。
以外のページがまだ作りかけ、確認漏れがあるようです。
慌てずに作って、再度確認を依頼してください。

2020-08-14 03:11 UTC, kazuyanakata commented
kaguya課題CSS(newsページ・recruitページ・contactページ)の初回実装を行いました。
レビューよろしくお願いいたします。

2020-08-24 00:47 UTC, kazuyanakata commented
**kaguya課題HOMEページレスポンシブ対応を行いました。**
レビューよろしくお願いいたします。

2020-08-25 01:34 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！
マークアップエンジニアがレビューすると指摘箇所があるかもしれませんがご容赦ください m(__)m

2020-09-06 02:49 UTC, kazuyanakata commented
**kaguya課題 news,recruit,contactページのレスポンシブ対応 初回実装を行いました。**

2020-10-23 11:44 UTC, merged